<?php

namespace App\Config;

use Ppci\Config\RightsPpci;

/**
 * List of all rights required by modules
 */
class Rights extends RightsPpci
{
    protected array $rights = [
        "parametre" => ["consult"],
        "debris_natureList" => ["consult"],
        "debris_natureChange" => ["param"],
        "debris_natureWrite" => ["param"],
        "debris_natureDelete" => ["param"],
        "prelevement_localisationList" => ["consult"],
        "prelevement_localisationChange" => ["param"],
        "prelevement_localisationWrite" => ["param"],
        "prelevement_localisationDelete" => ["param"],
        "prelevement_typeList" => ["consult"],
        "prelevement_typeChange" => ["param"],
        "prelevement_typeWrite" => ["param"],
        "prelevement_typeDelete" => ["param"],
        "cohorte_determinationList" => ["consult"],
        "cohorte_determinationChange" => ["param"],
        "cohorte_determinationWrite" => ["param"],
        "cohorte_determinationDelete" => ["param"],
        "eel_stadeList" => ["consult"],
        "eel_stadeChange" => ["param"],
        "eel_stadeWrite" => ["param"],
        "eel_stadeDelete" => ["param"],
        "release_stageList" => ["consult"],
        "release_stageChange" => ["param"],
        "release_stageWrite" => ["param"],
        "release_stageDelete" => ["param"],
        "nageoireList" => ["consult"],
        "nageoireChange" => ["param"],
        "nageoireWrite" => ["param"],
        "nageoireDelete" => ["param"],
        "stationList" => ["consult"],
        "stationChange" => ["param"],
        "stationWrite" => ["param"],
        "stationDelete" => ["param"],
        "stationGetPoints" => ["consult"],
        "mareeList" => ["consult"],
        "mareeChange" => ["param"],
        "mareeWrite" => ["param"],
        "mareeDelete" => ["param"],
        "enginTypeList" => ["consult"],
        "enginTypeChange" => ["param"],
        "enginTypeWrite" => ["param"],
        "enginTypeDelete" => ["param"],
        "readOnlyChange" => ["param"],
        "manipulateurList" => ["consult"],
        "manipulateurChange" => ["param"],
        "manipulateurWrite" => ["param"],
        "manipulateurDelete" => ["param"],
        "especeList" => ["consult"],
        "especeChange" => ["param"],
        "especeWrite" => ["param"],
        "especeDelete" => ["param"],
        "especeGetValues" => ["consult"],
        "especeSearchAjax" => ["manage"],
        "traitList" => ["consult"],
        "traitDisplay" => ["consult"],
        "traitChange" => ["manage"],
        "traitWrite" => ["manage"],
        "traitDelete" => ["manage"],
        "physicochimieChange" => ["consult"],
        "physicochimieWrite" => ["manage"],
        "echantillonChange" => ["consult"],
        "echantillonWrite" => ["manage"],
        "echantillonDelete" => ["manage"],
        "traitdebrisWrite" => ["manage"],
        "individuEelChange" => ["consult"],
        "individuEelWrite" => ["manage"],
        "individuEelDelete" => ["manage"],
        "individuSturioChange" => ["consult"],
        "individuSturioWrite" => ["manage"],
        "individuSturioDelete" => ["manage"],
        "sturioList" => ["consult"],
        "sturioDetail" => ["consult"],
        "traceImport" => ["manage"],
        "importTraceExec" => ["manage"],
        "tracePairing" => ["manage"],
        "tracePairingExec" => ["manage"],
        "importCinna" => ["manage"],
        "importCinnaExec" => ["manage"],
    ];
}
